server:
  port: 9999
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/carts/**
            - id: review-service
              uri: lb://REVIEW-SERVICE
              predicates:
                - Path=/reviews/**
                - Method=GET

            - id: delivery-service-deliveries
              uri: lb://DELIVERY-SERVICE
              predicates:
                - Path=/deliveries/**

            - id: delivery-service-drivers
              uri: lb://DELIVERY-SERVICE
              predicates:
                - Path=/drivers/**

            - id: delivery-service-freight
              uri: lb://DELIVERY-SERVICE
              predicates:
                - Path=/freight/**

            #- id: store
            #  uri: lb://STORE
            #  predicates:
            #    - Path=/stores/**
            #  filters:
            #   - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}

security:
  public-key: classpath:keys/public_key.pem

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: gateway,health,info