spring:
  application:
    name: search-service
  profiles:
    active: prod

security:
  private-key: classpath:keys/private_key.pem
  public-key: classpath:keys/public_key.pem

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
