spring:
  elasticsearch:
    uris: http://localhost:9201

  data:
    elasticsearch:
      repositories:
        enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-service-v1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.infnet.events
        spring.json.use.type.headers: false
eureka:
  client:
    register-with-eureka: false
    enabled: false
server:
  port: 8089