spring:
  application:
    name: user-service
  profiles:
    active: dev

security:
  private-key: classpath:keys/private_key.pem
  public-key: classpath:keys/public_key.pem

management:
  endpoints:
    web:
      exposure:
        include: health,info
api:
  endpoints:
    GEOCODE-FAKE-SERVICE