spring:
  application:
    name: user-service
  profiles:
    active: dev

security:
  private-key: classpath:keys/private_key.pem
  public-key: classpath:keys/public_key.pem

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
api:
  endpoints:
    GEOCODE-FAKE-SERVICE

resilience4j:
  ratelimiter:
    instances:
      loginLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1m
        timeoutDuration: 0

      registerLimiter:
        limitForPeriod: 3
        limitRefreshPeriod: 1m
        timeoutDuration: 0