spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
#    PERGUNTAR O portflow?currentSchema=container_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#        default_schema: PERGUNTAR
    show-sql: true

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    web:
      exposure:
        include: health,info

server:
  port: 0