spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  server:
    port: 8100
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus