services:
  # EUREKA
  discovery-server:
    build: ../discovery-server
    container_name: discovery-server

    ports:
      - "8761:8761"

    networks:
      - microservices-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # GATEWAY
  api-gateway:
    build: ../api-gateway
    container_name: api-gateway

    ports:
      - "9999:9999"

    networks:
      - microservices-network

    depends_on:
      discovery-server:
        condition: service_healthy

  # USER SERVICE
  user-service:
    build: ../user-service
    container_name: user-service

    networks:
      - microservices-network

    depends_on:
      discovery-server:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # POSTGRES
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  microservices-network:
