# Configuração do H2
spring.datasource.url=jdbc:h2:mem:carrinhodb
spring.datasource.driverClassName=org.h2.Driver
server.port=8081
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do H2 para você ver as tabelas no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra o SQL no console (bom para debug)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.data.redis.host=localhost
spring.data.redis.port=6379