services:

  postgres:
    image: postgres:17
    container_name: carservice-postgres

    environment:
      POSTGRES_DB: carservicedb
      POSTGRES_USER: car
      POSTGRES_PASSWORD: car

    ports:
      - "5432:5432"

    volumes:
      - carservice-postgres-data:/var/lib/postgresql/data
volumes:
  carservice-postgres-data: