server:
  port: 8086


spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: cart_service
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  server:
    port: 8086
  endpoints:
    web:
      exposure:
        include: gateway,health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  retry:
    instances:
      cartService:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.lang.Exception

  circuitbreaker:
    instances:
      cartService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true