spring:
  application:
    name: delivery-service

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: delivery_service
        format_sql: true

  kafka:
    bootstrap-servers: kafka:29092

    consumer:
      group-id: delivery-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.value.default.type: com.infnet.events.PaymentApprovatedEvent
        spring.json.trusted.packages: com.infnet.events
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      missing-topics-fatal: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers,circuitbreakerevents

  endpoint:
    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  retry:
    instances:
      freightService:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.lang.Exception

  circuitbreaker:
    instances:
      freightService:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true