spring:
  application:
    name: review-service
  profiles:
    active: prod

api:
  endpoints:
    store: STORE-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
