spring:
  application:
    name: review-service
  profiles:
    active: prod
api:
  endpoints:
    store: STORE-SERVICE
resilience4j:
  circuitbreaker:
    instances:
      storeValidation:
        slidingWindowSize: 4
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics