spring:
  application:
    name: store-service

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:29092 # Ou localhost:9092 se rodar localmente fora do docker
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 0 # Porta dedicada ao store-service
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name} # Isso ajuda a filtrar no Grafana depois
  tracing:
    sampling:
      probability: 1.0 # Define a amostragem para 100% (útil para desenvolvimento, regista todas as requisições)
    zipkin:
      tracing:
        endpoint: "http://zipkin:9411/api/v2/spans" # URL do contentor Zipkin no seu docker-compose